import os

from src.common.paths import (  # noqa: F401
    PROJECT_ROOT,
    ANOMALIB_MODELS_DIR,
    ANOMALIB_ONNX_DIR,
    ANOMALIB_MODEL_NAME,
    ROUTER_ONNX_PATH,
    DAGM_ONNX_PATH,
    KOLEKTOR_ONNX_PATH,
    MAGNETIC_TILE_ONNX_PATH,
    MVTEC_CATEGORIES,
    ROUTER_CLASSES,
    SUPERVISED_ROUTER_CLASSES,
)

ROUTER_CONFIDENCE_THRESHOLD = float(os.environ.get("VI_ROUTER_CONFIDENCE_THRESHOLD", "0.6"))
ANOMALY_REGION_THRESHOLD = float(os.environ.get("VI_ANOMALY_REGION_THRESHOLD", "0.5"))
ANOMALIB_DEVICE = os.environ.get("VI_ANOMALIB_DEVICE", "AUTO")
ANOMALIB_INFERENCER_CACHE_SIZE = int(os.environ.get("VI_ANOMALIB_INFERENCER_CACHE_SIZE", "3"))
